# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Generic-Genome-Browser
version:      1.64
version_from: 
installdirs:  site
requires:
    Bio::Perl:                     1.5
    CGI::Session:                  4.03
    GD:                            2.07
    IO::String:                    0
    Text::Shellwords:              1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
