=head1 Support for the chado database schema

Note that I consider chado support experimental still, as I am the only 
person that I know of who has tested it.

The chado schema ( http://www.gmod.org/schema ) is a comprehensive database
schema developed largely by developers at UC Berkeley and Harvard working
on FlyBase.  It is intended to be a generic database schema for model
organism use.  Its use with GBrowse is supported via a limited implementation
of the Das interface from BioPerl.  It is limited in that I implemented 
only what I needed of the interface and nothing more.

The chado adaptor works through three perl modules included in this 
distribution:

  lib/Bio/DB/Das/Chado.pm
  lib/Bio/DB/Das/Chado/Segment.pm
  lib/Bio/DB/Das/Chado/Segment/Feature.pm

These files are installed the in the BioPerl infastructure when 'make install' 
is run.

In addition to the standard chado schema, this adaptor requires a few
additional views and functions.  These are found in two files in the
chado CVS (or in a chado distribution, when one is available).  These are:

  schema/chado/modules/sequence/gff-bridge/sequence-gff-views.sql
  schema/chado/modules/sequence/gff-bridge/sequence-gff-funcs.pgsql

The easiest way to get these into the chado schema is to cat the files
to stdout and pipe that to a psql command:

  % cat sequence-gff-views.sql   | psql <chado-database-name>
  % cat sequence-gff-funcs.pgsql | psql <chado-database-name>

A sample chado configuration file is included in contrib/conf_files/.  
Since chado uses the Sequence Ontology for its controlled vocabulary, it
is quite likely that this configuration file should work for any
instance of chado once the database-specific parameters are set.

If you encounter any bugs or problems with this chado adaptor, please
let me know.

Scott Cain
cain@cshl.org
2003/08/20
