#!/bin/sh -e


case "$1" in
        upgrade|remove)
                if [ -x "/etc/init.d/gbrowse-slave" ]; then
                         /etc/init.d/gbrowse-slave stop || true
			 rm -f /etc/rc2.d/S*gbrowse-slave
			 rm -f /etc/rc2.d/K*gbrowse-slave
                fi
                sleep 2
        ;;
        deconfigure|failed-upgrade)
        ;;
        *)
                echo "prerm called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac


exit 0
