#!/bin/sh

export PERL5LIB=/home/lstein/projects/Generic-Genome-Browser/lib:/home/lstein/projects/bioperl-live

USER=www-data
RUNDIR=/var/run/gbrowse
LOGDIR=/var/log/gbrowse
PORT="8101 8102 8103"
VERBOSITY=3
NICE=0
