#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
    if 0; # not running under some shell

use strict;
use Bio::Graphics::Browser2::UserDB;
use CGI qw(:standard);

our $VERSION = '$Id: gbrowse_login,v 1.1 2009-08-27 20:33:23 idavies Exp $';

umask 022;
   
my $userdb = Bio::Graphics::Browser2::UserDB->new();

my %actions  = map {$_=>1} param('action');
my %callback;

my $user     = param('user');
my $pass     = param('pass');
my $email    = param('email');
my $userid   = param('session');
my $remember = param('remember');

my $old      = param('old_val');
my $new      = param('new_val');
my $column   = param('column');

my $confirm  = param('confirm');
my $openid   = param('openid');
my $option   = param('option');

if($actions{list_openid}) {
    print header('application/json');
    $userdb->do_list_openid($user)  if $actions{list_openid};
    exit 0;
}

if($actions{confirm_openid}) {
    my $arg;
    my $print = -1;

    foreach(param('callback')) {
        $arg   = $_           if($print == -1);
        $callback{$arg} = $_  if($print ==  1);
        $print = $print * -1;
    }

    print header('application/json');
    $userdb->do_confirm_openid(\%callback, $userid, $option);
    exit 0;
}

print header();

$userdb->do_validate			($user, $pass, $remember)				if $actions{validate};
$userdb->do_add_user_check		($user, $email, $pass, $userid)			if $actions{add_user_check};
$userdb->do_add_user			($user, $email, $pass, $userid)			if $actions{add_user};
$userdb->do_edit_confirmation	($email, $option)						if $actions{edit_confirmation};
$userdb->do_confirm_account		($user, $confirm)						if $actions{confirm_account};
$userdb->do_edit_details		($user, $column, $old, $new)			if $actions{edit_details};
$userdb->do_email_info			($email)								if $actions{email_info};
$userdb->do_delete_user			($user, $pass)							if $actions{delete_user};

$userdb->do_add_openid_user		($user, $openid, $userid, $remember)	if $actions{add_openid_user};
$userdb->do_check_openid		($openid, $userid, $option)				if $actions{check_openid};
$userdb->do_change_openid		($user, $pass, $openid, $option)		if $actions{change_openid};

exit 0;

__END__


##################################################################################
# Database - Copy this script into a file called login.sql and run with mysql
#              to create the tables required by the login application.
##################################################################################

/*  Usage: mysql -u root < /location/login.sql  */

DROP DATABASE IF EXISTS gbrowse_login;
CREATE DATABASE gbrowse_login;

GRANT ALL PRIVILEGES 
ON gbrowse_login.* 
TO 'gbrowse'@'localhost' identified by "gbrowse"
WITH GRANT OPTION;

use gbrowse_login;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    userid        varchar(32) not null PRIMARY key,
    username      varchar(32),
    email         varchar(64) not null UNIQUE key,
    pass          varchar(32) not null,
    remember          boolean not null,
    openid_only       boolean not null,
    confirmed         boolean not null,
    cnfrm_code    varchar(32) not null,
    last_login      timestamp not null,
    created          datetime not null
) ENGINE=InnoDB;

DROP TABLE IF EXISTS openid_users;
CREATE TABLE openid_users (
    userid        varchar(32) not null,
    username      varchar(32) not null,
    openid_url   varchar(128) not null PRIMARY key
) ENGINE=InnoDB;

DROP TABLE IF EXISTS uploads;
CREATE TABLE uploads (
    uploadid	       	varchar(32) not null PRIMARY key,
    ownerid				varchar(32) not null,
    subdir_path				   text,
    description				   text,
    creation_date			   datetime not null,
    modification_date		   datetime,
    sharing_policy			   ENUM('private', 'public', 'group', 'casual') not null
) ENGINE=InnoDB;
