#!/usr/bin/perl

use strict;
use lib
  '/home/lstein/projects/Generic-Genome-Browser/libnew',
  '/home/lstein/projects/Generic-Genome-Browser/lib';

use constant CONF_FILE =>
  '/etc/apache/gbrowse.new/GBrowse.conf';

use Bio::Graphics::Browser;
use Bio::Graphics::Browser::Render::HTML;

my $globals = Bio::Graphics::Browser->new(CONF_FILE) or die "Couldn't read globals";
my $render = Bio::Graphics::Browser::Render::HTML->new($globals);
$render->run;

1;


	
