#!/bin/sh

export PERL5LIB=$PERL5LIB

DAEMON=$INSTALLSCRIPT/gbrowse_slave
USER=$WWWUSER
PRELOAD=$CONF/slave_preload.conf
RUNDIR=/var/run/gbrowse
LOGDIR=/var/log/gbrowse
PREFORK=3
PORT="8101 8102 8103"
VERBOSITY=2
NICE=0
